### ISSUE TITLE
Questions about NPM package

### ISSUE THREAD

**Issue by moontai0724** [OneupNetwork/dialogify#13]
Hi maintainers,

We found there ia [a NPM package](https://www.npmjs.com/package/@oneup_network/dialogify) related to this repo, is it going to maintain anymore? Cause I saw the newer version is not updated to there.

By the way, some questions are mentioned in [this discussion](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/60439#issuecomment-1133969843_), could you please also review this?

> This package is named: `@oneup_network/dialogify` on NPM,
> but it has completely wrong entry point, so it cannot be installed/used through NPM (there is no `index.js` and there is no `main` property within package.json
> ```json
> "main": "./dist/dialogify.min.js",
> ```

_Originally posted by @peterblazejewicz in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/60439#issuecomment-1133969843_

And... I installed v1.0.3 from NPM, it downloaded all files in this repo, is this should be correct?

**Comment by porksteak** [comment]
Hi moontai0724,

抱歉這麼遲才回覆
請問現在的 1.0.5 版 npm 的設定是你上面提到的形式嗎?
當初上傳 npm 只是想讓其他人多一個管道取得或使用此專案, 沒太深入研究 npm 正確的使用方式, 還請見諒 😛
